[[redirects]]
  from = "/login"
  to = "/dist/login/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/dist/signup/index.html"
  status = 200

[[redirects]]
  from = "/servicesPrice"
  to = "/dist/servicesPrice/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"
