[[redirects]]
  from = "src/pages/login"
  to = "/dist/login/index.html"
  status = 200

[[redirects]]
  from = "src/pages/signup"
  to = "/dist/signup/index.html"
  status = 200

[[redirects]]
  from = "src/pages/servicesPrice"
  to = "/dist/servicesPrice/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"
