[[redirects]]
  from = "/login"
  to = "/login/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup/index.html"
  status = 200

[[redirects]]
  from = "/servicesPrice"
  to = "/servicesPrice/index.html"
  status = 200

[build]
  publish = "./dist"
  command = "sudo npm run build"
  functions = "./netlify/functions"
